# Site settings
author: Susan Meyers
title: "#Unlocking The Cod(ing) To My Future". 
header-img: img/home-bg.png
email: smmeyers24@gmail.com
copyright_name: Susan Meyers
description: > # this means to ignore newlines until "baseurl:"
  Introduction Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  susanmeyers

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
